<?php

class FinanceReports
{
    public const TYPES = ['payment_register', 'budget_summary', 'retention_report', 'ld_report', 'approved_unpaid', 'monthly_summary'];
    public const FORMATS = ['html', 'csv', 'json'];

    public static function cleanInput(array $input): array
    {
        $type = Security::cleanString((string)($input['type'] ?? 'monthly_summary'));
        $format = Security::cleanString((string)($input['format'] ?? 'html'));
        $filters = FinanceBudget::filters($input);

        return [
            'type' => in_array($type, self::TYPES, true) ? $type : 'monthly_summary',
            'format' => in_array($format, self::FORMATS, true) ? $format : 'html',
            'filters' => $filters,
            'auto_print' => !empty($input['print']) || !empty($input['auto_print']),
        ];
    }

    /**
     * Human labels for report type dropdowns.
     *
     * @return array<string, string>
     */
    public static function typeLabels(): array
    {
        $labels = [];
        foreach (self::TYPES as $type) {
            $labels[$type] = self::title($type);
        }
        return $labels;
    }

    /**
     * Which filter controls apply meaningfully for each report type.
     *
     * @return array{project:bool,q:bool,dates:bool,date_hint:string}
     */
    public static function filterSupport(string $type): array
    {
        return match ($type) {
            'payment_register' => [
                'project' => true,
                'q' => true,
                'dates' => true,
                'date_hint' => 'Filters by payment date.',
            ],
            'budget_summary' => [
                'project' => true,
                'q' => true,
                'dates' => false,
                'date_hint' => 'Budget is a current snapshot — date range is not applied.',
            ],
            'retention_report' => [
                'project' => true,
                'q' => true,
                'dates' => true,
                'date_hint' => 'Filters by planned release date.',
            ],
            'ld_report' => [
                'project' => true,
                'q' => true,
                'dates' => true,
                'date_hint' => 'Filters by last damage update date.',
            ],
            'approved_unpaid' => [
                'project' => true,
                'q' => true,
                'dates' => true,
                'date_hint' => 'Filters by IPC approval date.',
            ],
            default => [
                'project' => true,
                'q' => true,
                'dates' => true,
                'date_hint' => 'Filters by payment month / payment date.',
            ],
        };
    }

    public static function generate(string $type, array $filters = []): array
    {
        $type = in_array($type, self::TYPES, true) ? $type : 'monthly_summary';
        $queryFilters = self::mapFiltersForType($type, $filters);
        $title = self::title($type);
        $rows = match ($type) {
            'payment_register' => self::payments($queryFilters),
            'budget_summary' => FinanceBudget::projectRows($queryFilters, 500),
            'retention_report' => FinanceBudget::retentionRows($queryFilters, 500),
            'ld_report' => FinanceBudget::liquidatedDamageRows($queryFilters, 500),
            'approved_unpaid' => FinancePayment::approvedList($queryFilters, 500, 0),
            default => self::monthlySummary($queryFilters),
        };

        $summary = self::summary($type, $rows);

        return [
            'title' => $title,
            'type' => $type,
            'type_label' => $title,
            'org' => self::orgName(),
            'programme' => 'Trans-Nzoia Affordable Housing Programme',
            'generated_by' => Auth::name() ?: 'Finance',
            'generated_at' => date('Y-m-d H:i:s'),
            'generated_at_label' => format_datetime(date('Y-m-d H:i:s')),
            'filters' => $filters,
            'filter_labels' => self::filterLabels($filters),
            'filter_support' => self::filterSupport($type),
            'summary' => $summary,
            'summary_cards' => self::summaryCards($type, $rows, $summary),
            'columns' => self::columns($type),
            'rows' => $rows,
            'row_count' => count($rows),
        ];
    }

    public static function csv(array $report): string
    {
        $handle = fopen('php://temp', 'r+');
        fputcsv($handle, [$report['org'] ?? self::orgName()]);
        fputcsv($handle, [$report['title'] ?? 'Finance report']);
        fputcsv($handle, ['Generated by', $report['generated_by'] ?? '']);
        fputcsv($handle, ['Generated at', $report['generated_at'] ?? '']);
        foreach (($report['filter_labels'] ?? []) as $label => $value) {
            fputcsv($handle, [$label, $value]);
        }
        fputcsv($handle, []);
        $columns = $report['columns'] ?? [];
        fputcsv($handle, array_values($columns));
        foreach (($report['rows'] ?? []) as $row) {
            fputcsv($handle, array_map(static fn ($key) => self::cell($row, (string)$key), array_keys($columns)));
        }
        rewind($handle);
        return stream_get_contents($handle) ?: '';
    }

    /**
     * Professional printable HTML document (browser print / PDF via print dialog).
     */
    public static function html(array $report, bool $autoPrint = false): string
    {
        $columns = $report['columns'] ?? [];
        $title = (string)($report['title'] ?? 'Finance report');
        $org = (string)($report['org'] ?? self::orgName());
        $programme = (string)($report['programme'] ?? 'Trans-Nzoia Affordable Housing Programme');
        $rowCount = (int)($report['row_count'] ?? count($report['rows'] ?? []));
        $generatedBy = (string)($report['generated_by'] ?? '');
        $generatedAt = (string)($report['generated_at_label'] ?? $report['generated_at'] ?? '');
        $filterLabels = $report['filter_labels'] ?? [];
        $cards = $report['summary_cards'] ?? [];

        $css = self::printStyles();
        $html = '<!doctype html><html lang="en"><head><meta charset="utf-8">';
        $html .= '<meta name="viewport" content="width=device-width, initial-scale=1">';
        $html .= '<title>' . Security::e($title) . ' — ' . Security::e($org) . '</title>';
        $html .= '<style>' . $css . '</style></head><body class="report-print">';

        $html .= '<div class="sheet">';
        $html .= '<header class="sheet__header">';
        $html .= '<div class="sheet__brand"><div class="sheet__mark">AHP</div><div>';
        $html .= '<p class="sheet__org">' . Security::e($org) . '</p>';
        $html .= '<p class="sheet__programme">' . Security::e($programme) . '</p>';
        $html .= '</div></div>';
        $html .= '<div class="sheet__meta">';
        $html .= '<strong>Finance Report</strong>';
        $html .= '<span>Generated ' . Security::e($generatedAt) . '</span>';
        $html .= '<span>By ' . Security::e($generatedBy) . '</span>';
        $html .= '</div></header>';

        $html .= '<section class="sheet__title">';
        $html .= '<h1>' . Security::e($title) . '</h1>';
        $html .= '<p>' . Security::e((string)$rowCount) . ' record' . ($rowCount === 1 ? '' : 's') . ' · Official finance print view</p>';
        $html .= '</section>';

        if ($filterLabels !== []) {
            $html .= '<section class="sheet__filters"><h2>Applied filters</h2><ul>';
            foreach ($filterLabels as $label => $value) {
                $html .= '<li><span>' . Security::e((string)$label) . '</span><strong>' . Security::e((string)$value) . '</strong></li>';
            }
            $html .= '</ul></section>';
        }

        if ($cards !== []) {
            $html .= '<section class="sheet__cards">';
            foreach ($cards as $card) {
                $html .= '<article><em>' . Security::e((string)($card['label'] ?? '')) . '</em><strong>' . Security::e((string)($card['value'] ?? '')) . '</strong></article>';
            }
            $html .= '</section>';
        }

        $html .= '<div class="sheet__actions no-print">';
        $html .= '<button type="button" onclick="window.print()">Print / Save as PDF</button>';
        $html .= '<button type="button" onclick="window.close()">Close</button>';
        $html .= '</div>';

        $html .= '<table class="sheet__table"><thead><tr>';
        foreach ($columns as $key => $label) {
            $class = self::isMoneyKey((string)$key) ? ' class="money"' : '';
            $html .= '<th' . $class . '>' . Security::e((string)$label) . '</th>';
        }
        $html .= '</tr></thead><tbody>';

        if (($report['rows'] ?? []) === []) {
            $html .= '<tr><td colspan="' . max(1, count($columns)) . '" class="empty">No records found for the selected filters.</td></tr>';
        } else {
            foreach ($report['rows'] as $row) {
                $html .= '<tr>';
                foreach (array_keys($columns) as $key) {
                    $class = self::isMoneyKey((string)$key) ? ' class="money"' : '';
                    $html .= '<td' . $class . '>' . Security::e(self::cell($row, (string)$key)) . '</td>';
                }
                $html .= '</tr>';
            }
        }

        $html .= '</tbody></table>';

        $html .= '<footer class="sheet__footer">';
        $html .= '<p>Confidential — for authorised County / programme finance use only.</p>';
        $html .= '<p>' . Security::e($org) . ' · ' . Security::e($title) . ' · Page printed from the finance portal</p>';
        $html .= '</footer></div>';

        if ($autoPrint) {
            $html .= '<script>window.addEventListener("load",function(){setTimeout(function(){window.print();},250);});</script>';
        }

        $html .= '</body></html>';
        return $html;
    }

    public static function recordRun(int $userId, string $type, string $format, array $filters, int $rowCount, string $status = 'generated'): void
    {
        try {
            Database::query(
                'INSERT INTO report_runs (user_id, report_type, format, filters_json, row_count, status, created_at)
                 VALUES (?, ?, ?, ?, ?, ?, NOW())',
                [$userId, 'finance_' . $type, $format, json_encode($filters, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE), $rowCount, $status]
            );
        } catch (Throwable) {
        }
    }

    public static function recentRuns(int $limit = 8): array
    {
        $rows = Database::fetchAll(
            "SELECT rr.*, CONCAT(u.first_name, ' ', u.last_name) AS user_name
             FROM report_runs rr
             LEFT JOIN users u ON u.id = rr.user_id
             WHERE rr.report_type LIKE 'finance_%'
             ORDER BY rr.created_at DESC
             LIMIT " . max(1, $limit)
        );

        return array_map(static function (array $row): array {
            $type = (string)preg_replace('/^finance_/', '', (string)($row['report_type'] ?? ''));
            $row['type_key'] = $type;
            $row['type_label'] = self::title($type !== '' ? $type : 'monthly_summary');
            $row['format_label'] = match (strtolower((string)($row['format'] ?? ''))) {
                'csv' => 'CSV export',
                'json' => 'JSON',
                'html', 'print' => 'Print view',
                'preview' => 'On-screen preview',
                default => strtoupper((string)($row['format'] ?? 'report')),
            };
            return $row;
        }, $rows);
    }

    /**
     * Map UI filters to each report consumer's expected keys.
     */
    private static function mapFiltersForType(string $type, array $filters): array
    {
        $mapped = $filters;

        if ($type === 'approved_unpaid') {
            if (!empty($filters['date_from']) && empty($filters['approved_from'])) {
                $mapped['approved_from'] = $filters['date_from'];
            }
            if (!empty($filters['date_to']) && empty($filters['approved_to'])) {
                $mapped['approved_to'] = $filters['date_to'];
            }
        }

        // Budget is a live snapshot — strip date keys so callers stay honest.
        if ($type === 'budget_summary') {
            unset($mapped['date_from'], $mapped['date_to'], $mapped['approved_from'], $mapped['approved_to']);
        }

        return $mapped;
    }

    private static function payments(array $filters): array
    {
        $where = ["pay.status = 'processed'"];
        $bindings = [];
        if (!empty($filters['project_id'])) {
            $where[] = 'p.id = ?';
            $bindings[] = (int)$filters['project_id'];
        }
        foreach (['date_from' => '>=', 'date_to' => '<='] as $key => $op) {
            $date = trim((string)($filters[$key] ?? ''));
            if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $date)) {
                $where[] = "pay.payment_date {$op} ?";
                $bindings[] = $date;
            }
        }
        $q = trim((string)($filters['q'] ?? ''));
        if ($q !== '') {
            $where[] = '(p.name LIKE ? OR pay.reference_no LIKE ? OR contractor.first_name LIKE ? OR contractor.last_name LIKE ?)';
            $term = '%' . $q . '%';
            array_push($bindings, $term, $term, $term, $term);
        }

        return Database::fetchAll(
            "SELECT pay.*, i.ipc_number, p.name AS project_name,
                    CONCAT(contractor.first_name, ' ', contractor.last_name) AS contractor_name,
                    CONCAT(processor.first_name, ' ', processor.last_name) AS processed_by_name
             FROM payments pay
             JOIN ipcs i ON i.id = pay.ipc_id
             JOIN projects p ON p.id = pay.project_id
             JOIN users contractor ON contractor.id = i.contractor_id
             JOIN users processor ON processor.id = pay.processed_by
             WHERE " . implode(' AND ', $where) . "
             ORDER BY pay.payment_date DESC, pay.id DESC
             LIMIT 500",
            $bindings
        );
    }

    private static function monthlySummary(array $filters): array
    {
        $where = ["pay.status = 'processed'"];
        $bindings = [];

        if (!empty($filters['project_id'])) {
            $where[] = 'p.id = ?';
            $bindings[] = (int)$filters['project_id'];
        }
        foreach (['date_from' => '>=', 'date_to' => '<='] as $key => $op) {
            $date = trim((string)($filters[$key] ?? ''));
            if (preg_match('/^\d{4}-\d{2}-\d{2}$/', $date)) {
                $where[] = "pay.payment_date {$op} ?";
                $bindings[] = $date;
            }
        }
        $q = trim((string)($filters['q'] ?? ''));
        if ($q !== '') {
            $where[] = '(p.name LIKE ? OR pay.reference_no LIKE ?)';
            $term = '%' . $q . '%';
            array_push($bindings, $term, $term);
        }

        return Database::fetchAll(
            "SELECT DATE_FORMAT(pay.payment_date, '%Y-%m') AS month_label,
                    COUNT(*) AS payment_count,
                    COALESCE(SUM(pay.amount), 0) AS paid_amount,
                    COALESCE(SUM(i.retention_amount), 0) AS retention_amount
             FROM payments pay
             JOIN ipcs i ON i.id = pay.ipc_id
             JOIN projects p ON p.id = pay.project_id
             WHERE " . implode(' AND ', $where) . "
             GROUP BY DATE_FORMAT(pay.payment_date, '%Y-%m')
             ORDER BY month_label DESC
             LIMIT 24",
            $bindings
        );
    }

    private static function columns(string $type): array
    {
        return match ($type) {
            'payment_register' => [
                'reference_no' => 'Reference',
                'ipc_number' => 'IPC',
                'project_name' => 'Project',
                'contractor_name' => 'Contractor',
                'payment_date' => 'Date',
                'amount' => 'Amount',
            ],
            'budget_summary' => [
                'name' => 'Project',
                'status' => 'Status',
                'contract_sum' => 'Contract Sum',
                'paid_amount' => 'Paid',
                'approved_unpaid' => 'Approved Unpaid',
                'retention_held' => 'Retention',
                'ld_value' => 'LDs',
                'balance_amount' => 'Balance',
                'risk_label' => 'Signal',
            ],
            'retention_report' => [
                'project_name' => 'Project',
                'ipc_number' => 'IPC',
                'status' => 'Status',
                'total_held' => 'Held',
                'released_amount' => 'Released',
                'balance_amount' => 'Balance',
                'release_date' => 'Release Date',
            ],
            'ld_report' => [
                'project_name' => 'Project',
                'status' => 'Status',
                'days_overdue' => 'Days',
                'rate_per_day' => 'Daily Rate',
                'total_ld' => 'Total',
                'ipc_number' => 'Linked IPC',
            ],
            'approved_unpaid' => [
                'ipc_number' => 'IPC',
                'project_name' => 'Project',
                'contractor_name' => 'Contractor',
                'approved_at' => 'Approved',
                'gross_amount' => 'Gross',
                'retention_amount' => 'Retention',
                'outstanding_amount' => 'Net Payable',
            ],
            default => [
                'month_label' => 'Month',
                'payment_count' => 'Payments',
                'paid_amount' => 'Paid',
                'retention_amount' => 'Retention',
            ],
        };
    }

    public static function title(string $type): string
    {
        return match ($type) {
            'payment_register' => 'Payment Register',
            'budget_summary' => 'Budget Summary',
            'retention_report' => 'Retention Report',
            'ld_report' => 'Liquidated Damages Report',
            'approved_unpaid' => 'Approved Unpaid IPCs',
            'monthly_summary' => 'Monthly Finance Summary',
            default => 'Finance Report',
        };
    }

    private static function summary(string $type, array $rows): array
    {
        $base = ['rows' => count($rows), 'type' => self::title($type)];

        return match ($type) {
            'payment_register' => $base + [
                'total_paid' => array_sum(array_map(static fn ($r) => (float)($r['amount'] ?? 0), $rows)),
            ],
            'budget_summary' => $base + [
                'contract_value' => array_sum(array_map(static fn ($r) => (float)($r['contract_sum'] ?? 0), $rows)),
                'paid_value' => array_sum(array_map(static fn ($r) => (float)($r['paid_amount'] ?? 0), $rows)),
                'approved_unpaid' => array_sum(array_map(static fn ($r) => (float)($r['approved_unpaid'] ?? 0), $rows)),
            ],
            'retention_report' => $base + [
                'held' => array_sum(array_map(static fn ($r) => (float)($r['total_held'] ?? 0), $rows)),
                'balance' => array_sum(array_map(static fn ($r) => (float)($r['balance_amount'] ?? 0), $rows)),
            ],
            'ld_report' => $base + [
                'total_ld' => array_sum(array_map(static fn ($r) => (float)($r['total_ld'] ?? 0), $rows)),
            ],
            'approved_unpaid' => $base + [
                'net_payable' => array_sum(array_map(static fn ($r) => (float)($r['outstanding_amount'] ?? 0), $rows)),
            ],
            default => $base + [
                'paid_value' => array_sum(array_map(static fn ($r) => (float)($r['paid_amount'] ?? 0), $rows)),
                'payment_count' => array_sum(array_map(static fn ($r) => (int)($r['payment_count'] ?? 0), $rows)),
            ],
        };
    }

    /**
     * @return list<array{label:string,value:string}>
     */
    private static function summaryCards(string $type, array $rows, array $summary): array
    {
        $cards = [
            ['label' => 'Records', 'value' => format_number((int)($summary['rows'] ?? count($rows)))],
        ];

        return match ($type) {
            'payment_register' => array_merge($cards, [
                ['label' => 'Total paid', 'value' => format_money((float)($summary['total_paid'] ?? 0))],
            ]),
            'budget_summary' => array_merge($cards, [
                ['label' => 'Contract value', 'value' => format_money((float)($summary['contract_value'] ?? 0))],
                ['label' => 'Paid', 'value' => format_money((float)($summary['paid_value'] ?? 0))],
                ['label' => 'Approved unpaid', 'value' => format_money((float)($summary['approved_unpaid'] ?? 0))],
            ]),
            'retention_report' => array_merge($cards, [
                ['label' => 'Held', 'value' => format_money((float)($summary['held'] ?? 0))],
                ['label' => 'Open balance', 'value' => format_money((float)($summary['balance'] ?? 0))],
            ]),
            'ld_report' => array_merge($cards, [
                ['label' => 'Damages total', 'value' => format_money((float)($summary['total_ld'] ?? 0))],
            ]),
            'approved_unpaid' => array_merge($cards, [
                ['label' => 'Net payable', 'value' => format_money((float)($summary['net_payable'] ?? 0))],
            ]),
            default => array_merge($cards, [
                ['label' => 'Payments', 'value' => format_number((int)($summary['payment_count'] ?? 0))],
                ['label' => 'Paid value', 'value' => format_money((float)($summary['paid_value'] ?? 0))],
            ]),
        };
    }

    /**
     * @return array<string, string>
     */
    private static function filterLabels(array $filters): array
    {
        $labels = [];
        if (!empty($filters['project_id'])) {
            $project = Database::fetch('SELECT name FROM projects WHERE id = ? LIMIT 1', [(int)$filters['project_id']]);
            $labels['Project'] = (string)($project['name'] ?? ('#' . (int)$filters['project_id']));
        }
        if (!empty($filters['q'])) {
            $labels['Search'] = (string)$filters['q'];
        }
        if (!empty($filters['date_from'])) {
            $labels['From'] = format_date((string)$filters['date_from']);
        }
        if (!empty($filters['date_to'])) {
            $labels['To'] = format_date((string)$filters['date_to']);
        }
        if (!empty($filters['status'])) {
            $labels['Status'] = status_label((string)$filters['status']);
        }
        if (!empty($filters['risk'])) {
            $labels['Signal'] = status_label((string)$filters['risk']);
        }
        return $labels;
    }

    private static function orgName(): string
    {
        try {
            if (class_exists('SystemConfig')) {
                $name = trim((string)(SystemConfig::get('app_name') ?? SystemConfig::get('site_name') ?? ''));
                if ($name !== '') {
                    return $name;
                }
            }
        } catch (Throwable) {
        }

        return 'County Government of Trans-Nzoia';
    }

    private static function isMoneyKey(string $key): bool
    {
        return (bool)preg_match('/(amount|value|sum|held|released|balance|rate|ld|retention|gross|net|paid|unpaid)/i', $key);
    }

    public static function cell(array $row, string $key): string
    {
        $value = $row[$key] ?? '';

        if ($key === 'status' || $key === 'risk_label') {
            if ($key === 'risk_label') {
                return (string)$value;
            }
            return status_label((string)$value);
        }

        if ($key === 'payment_count' || $key === 'days_overdue') {
            return format_number((float)$value);
        }

        if (is_numeric($value) && self::isMoneyKey($key)) {
            return format_money((float)$value);
        }

        if (str_ends_with($key, '_at') || str_ends_with($key, '_date')) {
            return format_date($value !== '' && $value !== null ? (string)$value : null);
        }

        if ($key === 'ipc_number' && $value !== '' && $value !== null) {
            return 'IPC #' . $value;
        }

        if ($key === 'month_label' && is_string($value) && preg_match('/^\d{4}-\d{2}$/', $value)) {
            $ts = strtotime($value . '-01');
            return $ts ? date('M Y', $ts) : $value;
        }

        return (string)$value;
    }

    private static function printStyles(): string
    {
        return <<<'CSS'
:root{--ink:#07111f;--muted:#5b6b84;--line:#d5deea;--soft:#f4f8f1;--green:#123d02;--lime:#a7f337}
*{box-sizing:border-box}
body{margin:0;background:#e8eef5;color:var(--ink);font:13px/1.45 "Segoe UI",Arial,sans-serif}
.sheet{max-width:1100px;margin:18px auto;background:#fff;border:1px solid var(--line);border-radius:10px;padding:28px 32px 24px;box-shadow:0 10px 30px rgba(7,17,31,.08)}
.sheet__header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;padding-bottom:16px;border-bottom:3px solid var(--green)}
.sheet__brand{display:flex;gap:12px;align-items:center}
.sheet__mark{width:48px;height:48px;border-radius:10px;background:linear-gradient(145deg,var(--green),#1f5c08);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:800;letter-spacing:.04em}
.sheet__org{margin:0;font-size:15px;font-weight:800}
.sheet__programme{margin:2px 0 0;color:var(--muted);font-size:12px}
.sheet__meta{text-align:right;display:grid;gap:2px;color:var(--muted);font-size:12px}
.sheet__meta strong{color:var(--green);font-size:12px;text-transform:uppercase;letter-spacing:.04em}
.sheet__title{margin:18px 0 12px}
.sheet__title h1{margin:0 0 4px;font-size:22px;line-height:1.2}
.sheet__title p{margin:0;color:var(--muted)}
.sheet__filters{margin:0 0 14px;padding:12px 14px;border:1px solid var(--line);border-radius:8px;background:var(--soft)}
.sheet__filters h2{margin:0 0 8px;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--muted)}
.sheet__filters ul{list-style:none;margin:0;padding:0;display:flex;flex-wrap:wrap;gap:8px 16px}
.sheet__filters li{display:flex;gap:8px;align-items:baseline}
.sheet__filters span{color:var(--muted);font-size:11px;text-transform:uppercase}
.sheet__cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:10px;margin:0 0 16px}
.sheet__cards article{border:1px solid var(--line);border-radius:8px;padding:10px 12px;background:#fff}
.sheet__cards em{display:block;font-style:normal;color:var(--muted);font-size:11px;text-transform:uppercase;font-weight:700}
.sheet__cards strong{display:block;margin-top:4px;font-size:14px}
.sheet__actions{display:flex;gap:8px;margin:0 0 14px}
.sheet__actions button{appearance:none;border:1px solid var(--green);background:var(--green);color:#fff;border-radius:8px;padding:9px 14px;font:inherit;font-weight:700;cursor:pointer}
.sheet__actions button:last-child{background:#fff;color:var(--green)}
.sheet__table{width:100%;border-collapse:collapse;margin-top:4px}
.sheet__table th,.sheet__table td{border:1px solid var(--line);padding:8px 10px;vertical-align:top;text-align:left}
.sheet__table th{background:var(--soft);font-size:11px;text-transform:uppercase;letter-spacing:.03em;color:#334155}
.sheet__table td.money,.sheet__table th.money{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}
.sheet__table td.empty{text-align:center;color:var(--muted);padding:22px}
.sheet__footer{margin-top:18px;padding-top:12px;border-top:1px solid var(--line);color:var(--muted);font-size:11px}
.sheet__footer p{margin:0 0 4px}
@media print{
  body{background:#fff}
  .sheet{margin:0;max-width:none;border:0;border-radius:0;box-shadow:none;padding:0}
  .no-print,.sheet__actions{display:none!important}
  .sheet__table th{-webkit-print-color-adjust:exact;print-color-adjust:exact}
  @page{margin:14mm}
}
@media (max-width:720px){
  .sheet{margin:0;border-radius:0;padding:16px}
  .sheet__header{flex-direction:column}
  .sheet__meta{text-align:left}
}
CSS;
    }
}
